// ============================================================
// build.mjs — 单一内容源生成器
// 用法：
//   node tools/build.mjs seed      # 从现有 index.html + zh-i18n.js 生成 content.json 与 tools/template.html
//   node tools/build.mjs build     # 用 content.json 重新生成 index.html 与 js/zh-i18n.js
// 约定：结构改动才需重新 seed；日常文字修改只编辑 content.json（或经编辑台）。
// ============================================================
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = process.env.PI_SITE ? join(dirname(fileURLToPath(import.meta.url)), '..', process.env.PI_SITE) : join(dirname(fileURLToPath(import.meta.url)), '..');
const IDX = join(ROOT, 'index.html');
const ZH  = join(ROOT, 'js', 'zh-i18n.js');
const CONTENT = join(ROOT, 'content.json');
const TEMPLATE = join(ROOT, 'tools', 'template.html');

const VOID = new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);

// 取 data-i18n="KEY" 元素的 (前缀, 内容, 后缀)
export function splitAtKey(html, key) {
  const attr = `data-i18n="${key}"`;
  const ai = html.indexOf(attr);
  if (ai === -1) return null;
  const openEnd = html.indexOf('>', ai);
  const prefix = html.slice(0, openEnd + 1);
  let i = openEnd + 1, stack = [];
  while (i < html.length) {
    const lt = html.indexOf('<', i);
    if (lt === -1) break;
    if (html.startsWith('<!--', lt)) { const ce = html.indexOf('-->', lt); if (ce === -1) break; i = ce + 3; continue; }
    const gt = html.indexOf('>', lt);
    if (gt === -1) break;
    const inner = html.slice(lt + 1, gt).trim();
    if (inner.startsWith('/')) {          // 闭合标签
      if (stack.length === 0) {
        return { prefix, content: html.slice(openEnd + 1, lt), suffix: html.slice(lt) };
      }
      stack.pop();
    } else if (!inner.endsWith('/') && !inner.startsWith('!')) {
      const name = (inner.match(/^[a-zA-Z0-9]+/) || [''])[0].toLowerCase();
      if (name && !VOID.has(name)) stack.push(name);
    }
    i = gt + 1;
  }
  return { prefix, content: html.slice(openEnd + 1), suffix: '' };
}

export function keysIn(html) {
  const out = [];
  for (const m of html.matchAll(/data-i18n="([^"]+)"/g)) if (!out.includes(m[1])) out.push(m[1]);
  return out;
}

function loadZh() {
  try {
    const code = readFileSync(ZH, 'utf8');
    const ctx = { window: {} };
    vm.createContext(ctx);
    vm.runInContext(code, ctx);
    return ctx.window.I18N_ZH || {};
  } catch { return {}; }
}

function sentinel(k) { return `<!--__I18N_${k}__-->`; }

export function buildContentFile() {
  const html = readFileSync(IDX, 'utf8');
  const zh = loadZh();
  const content = {};
  for (const k of keysIn(html)) {
    const r = splitAtKey(html, k);
    if (!r) { console.warn('skip(not found):', k); continue; }
    content[k] = { en: r.content, zh: zh[k] ?? '' };
  }
  writeFileSync(CONTENT, JSON.stringify(content, null, 1) + '\n');
  // 模板 = 每处内容替换为哨兵
  let tpl = html;
  for (const k of Object.keys(content)) {
    const r = splitAtKey(tpl, k);
    if (!r) continue;
    tpl = tpl.replace(r.content, sentinel(k));
  }
  writeFileSync(TEMPLATE, tpl);
  console.log(`content.json: ${Object.keys(content).length} keys; template.html 已生成`);
}

export function render() {
  if (!existsSync(CONTENT) || !existsSync(TEMPLATE)) { console.error('先运行 seed'); process.exit(1); }
  const content = JSON.parse(readFileSync(CONTENT, 'utf8'));
  const tpl = readFileSync(TEMPLATE, 'utf8');
  let html = tpl;
  for (const k of Object.keys(content)) {
    if (!html.includes(sentinel(k))) { console.warn('模板缺哨兵:', k); continue; }
    html = html.replace(sentinel(k), content[k].en ?? '');
  }
  writeFileSync(IDX, html);
  const entries = Object.entries(content).map(([k, v]) => {
    const en = v.zh ?? '';
    return `  ${JSON.stringify(k)}: ${JSON.stringify(en)},`;
  });
  const head = '/* AUTO-GENERATED by tools/build.mjs — 请勿手改；内容在 content.json */\nwindow.I18N_ZH = {\n';
  const tail = '\n};\n';
  writeFileSync(ZH, head + entries.join('\n') + tail);
  console.log(`index.html 与 zh-i18n.js 已由 content.json 重新生成（${Object.keys(content).length} keys）`);
}

const cmd = process.argv[2];
const isMain = !!process.argv[1] && process.argv[1].endsWith('build.mjs');
if (isMain) {
  if (cmd === 'seed') buildContentFile();
  else if (cmd === 'build') render();
  else console.log('用法: node tools/build.mjs seed|build');
}
